### ISSUE TITLE
PRO market data 

### ISSUE THREAD

**Issue by MartyIX** [BTCChina/btcc-issues#1]
Hi,

I have found that  `MDEntrySize` field in `MarketDataIncrementalRefresh` message represents volume difference when `MDUpdateAction=change` and not the new value. This makes construction of the orderbook very hard. (https://www.btcc.com/apidocs/pro-exchange-market-fix-api#marketdataincrementalrefresh-x-)

**Example:**

1) Let's say there are available to sale 3 BTC for 5215 CNY. 
2) Afterwards, I get `MarketDataIncrementalRefresh` where `MDUpdateAction=change` and `MDEntrySize=-1`. 
3) The new volume in orderbook is equal to 2 BTC for 5215 CNY price.

(It would be much easier to obtain `MDEntrySize=2`, i.e. the new volume)

Best regards,
Marty

PS: A separate issue is that `MarketDataSnapshotFullRefresh` message returns only top of the book.

**Comment by MartyIX** [comment]
@mikaelw Is this the type of issues, you are looking for? Thanks

**Comment by silence-vin** [comment]
@MartyIX For IncrementalRefresh, the refresh action is base on the same price but all the volume of this price.  And currently the  incrementalRefresh request will tell customers the increase or decrease of 5215, not the remaining volume.

If customers want to know the remaining volume of one price, I think snapshotFullRefresh would be better.

**Comment by MartyIX** [comment]
@silence-vin Yes, I understand that I receive the increase or the decrease. The thing is that I don't have full orderbook because `MarketDataSnapshotFullRefresh` returns only *TWO* records (top BID and top ASK). So I can't compute the remaining volume.

**Comment by MartyIX** [comment]
@silence-vin I have noticed that the sample of yours https://github.com/JoanJia/btcc-pro-fix-java-simplified/blob/master/src/main/java/com/btcc/javafx/MainController.java#L405 uses a simple strategy that it downloads market data every 5 seconds. That's certainly a workaround. But it creates heavier load on your server and it's not really real-time.

**Comment by silence-vin** [comment]
@MartyIX Thanks. I'll test this situation and work on it with my colleagues. I'll update here once we have progress.

**Comment by MartyIX** [comment]
@silence-vin Were you able to reproduce the issue? Thank you

**Comment by silence-vin** [comment]
@MartyIX Yes, and this is in our issue list which will be fixed in our next fix server release.
